CREATE DATABASE db_ak;
USE db_ak;
CREATE TABLE `tbl_products` (`product_id` INT NOT NULL AUTO_INCREMENT , `product_name` VARCHAR(255) NOT NULL , `product_description` VARCHAR(255) NOT NULL , `product_category` VARCHAR(255) NOT NULL , `product_price` FLOAT NOT NULL , `in_stock` INT NOT NULL , `product_added` DATE NOT NULL , `product_image` VARCHAR(255) NOT NULL , `feature` VARCHAR(255) NOT NULL , `long_description` VARCHAR(255) NOT NULL , PRIMARY KEY (`product_id`)) ENGINE = InnoDB;
CREATE TABLE `tbl_cart` (`cart_id` INT NOT NULL AUTO_INCREMENT , `product_id` INT NOT NULL , `quantity` INT NOT NULL;
INSERT INTO `tbl_products` (`product_id`, `product_name`, `product_description`, `product_category`, `product_price`, `in_stock`, `product_added`, `product_image`, `feature`, `long_description`) VALUES
(1, 'Whey Protein Powder', 'Whey protein powder, 2 lbs, chocolate flavor.', 'protein', 39.99, 180, '2024-08-02', 'whey_protein_powder.jpg', 'normal', 'Whey protein powder is a popular dietary supplement used to enhance muscle growth and recovery. This 2 lbs pack comes in a delicious chocolate flavor, perfect for mixing with water or milk. It is an excellent source of high-quality protein that provides all essential amino acids. Ideal for athletes and fitness enthusiasts, it helps in muscle repair and growth.'),
(2, 'Casein Protein Powder', 'Slow-digesting casein protein powder, 2 lbs, vanilla flavor.', 'protein', 42.99, 150, '2024-08-02', 'casein_protein_powder.jpg', 'recently added', 'Casein protein powder is a slow-digesting protein perfect for nighttime use. This 2 lbs pack in vanilla flavor provides a steady release of amino acids, making it ideal for muscle recovery and growth while you sleep. It helps reduce muscle breakdown and supports sustained muscle growth. Perfect for athletes and bodybuilders who need long-lasting protein support.'),
(3, 'Vegan Protein Powder', 'Plant-based protein powder, 2 lbs, chocolate flavor.', 'protein', 45.99, 130, '2024-08-02', 'vegan_protein_powder.jpg', 'recently added', 'Vegan protein powder is a plant-based protein source perfect for those following a vegan diet. This 2 lbs pack in chocolate flavor is made from high-quality plant proteins like pea and rice, offering a complete amino acid profile. It supports muscle growth and recovery, making it an excellent choice for athletes and fitness enthusiasts. Free from dairy and gluten.'),
(4, 'Pre-Workout Supplement', 'Energy-boosting pre-workout powder, 300g, fruit punch flavor.', 'supplements', 29.99, 150, '2024-08-02', 'pre_workout_supplement.jpg', 'recently added', 'Pre-workout supplement is designed to enhance your workout performance. This 300g pack in fruit punch flavor boosts energy, focus, and endurance. It contains ingredients like caffeine, beta-alanine, and creatine to help you push through intense workouts. Ideal for athletes and fitness enthusiasts looking for an extra edge during their training sessions.'),
(5, 'Weight Gainer Blend', '(Previously Impact Weight Gainer) The perfect way to increase strength and size', 'protein', 44.99, 2, '2024-08-01', 'protein_gainer.jpg', 'featured', 'Weight Gainer Blend is the perfect supplement for increasing strength and size. This high-calorie formula provides a balanced mix of proteins, carbohydrates, and fats to support muscle growth and recovery. Ideal for athletes and bodybuilders looking to gain muscle mass and improve performance. Easy to mix and available in delicious flavors.'),
(6, 'BCAA Supplement', 'Branched-Chain Amino Acids supplement, 400g, citrus flavor.', 'supplements', 25.99, 140, '2024-08-02', 'bcaa_supplement.jpg', 'recently added', 'BCAA supplement provides essential branched-chain amino acids that support muscle recovery and growth. This 400g pack in citrus flavor helps reduce muscle soreness and fatigue. It is ideal for athletes and fitness enthusiasts who engage in intense training. Easy to mix and consume before or after workouts for optimal results.'),
(7, 'Creatine Monohydrate', 'Creatine monohydrate powder, 300g.', 'creatine', 19.99, 160, '2024-08-02', 'creatine_monohydrate.jpg', 'featured', 'Creatine monohydrate is a popular supplement for enhancing athletic performance. This 300g pack helps increase strength, power, and muscle mass. Ideal for high-intensity workouts, it supports ATP production, allowing you to train harder and longer. Suitable for athletes, bodybuilders, and fitness enthusiasts looking to improve their performance.'),
(8, 'Micronized Creatine', 'Micronized creatine powder, 500g.', 'creatine', 24.99, 100, '2024-08-02', 'micronized_creatine.jpg', 'featured', 'Micronized creatine offers superior absorption and effectiveness. This 500g pack supports increased strength, power, and muscle mass. It helps in ATP production, enhancing performance during high-intensity training. Ideal for athletes and bodybuilders seeking to improve their workout efficiency. Mixes easily with water or your favorite beverage.'),
(9, 'Creatine Capsules', 'Creatine monohydrate capsules, 120 count.', 'creatine', 29.99, 90, '2024-08-02', 'creatine_capsules.jpg', 'recently added', 'Creatine monohydrate capsules provide a convenient way to enhance your performance. This pack contains 120 capsules, each delivering a potent dose of creatine. Supports increased strength, power, and muscle mass. Ideal for athletes and fitness enthusiasts who prefer capsules over powder. Easy to consume before or after workouts for optimal results.'),
(10, 'Dumbbell Set', 'Adjustable dumbbell set with a total weight of 40 lbs.', 'equipment', 59.99, 100, '2024-08-02', 'dumbbell_set.jpg', 'recently added', 'Dumbbell set is perfect for home workouts and strength training. This adjustable set includes weights totaling 40 lbs, allowing you to customize your workout intensity. Suitable for a variety of exercises targeting different muscle groups. Ideal for fitness enthusiasts looking to build strength and tone muscles at home.'),
(11, 'Kettlebell', 'Cast iron kettlebell with vinyl coating, 20 lbs.', 'equipment', 34.99, 150, '2024-08-02', 'kettlebell.jpg', 'normal', 'Kettlebell is a versatile piece of equipment for strength and conditioning workouts. This 20 lbs cast iron kettlebell with a vinyl coating provides a secure grip and durability. Ideal for exercises like swings, squats, and presses. Suitable for all fitness levels, from beginners to advanced athletes.'),
(12, 'Treadmill', 'Electric treadmill with adjustable incline and speed settings.', 'equipment', 499.99, 20, '2024-08-02', 'treadmill.jpg', 'normal', 'Electric treadmill is ideal for home cardio workouts. Features adjustable incline and speed settings to customize your training intensity. Comes with a built-in LCD display to track your progress, including time, distance, speed, and calories burned. Suitable for all fitness levels, providing a convenient way to stay active indoors.'),
(13, 'Exercise Bike', 'Stationary exercise bike with LCD display and adjustable resistance.', 'equipment', 299.99, 30, '2024-08-02', 'exercise_bike.jpg', 'normal', 'Stationary exercise bike is perfect for cardiovascular workouts at home. Features an LCD display to monitor your progress and adjustable resistance for varied workout intensity. Comfortable seat and pedals ensure a smooth and effective ride. Ideal for fitness enthusiasts looking to improve their endurance and overall fitness.'),
(14, 'Pull-Up Bar', 'Doorway pull-up bar with multiple grip positions.', 'equipment', 29.99, 80, '2024-08-02', 'pull_up_bar.jpg', 'normal', 'Pull-up bar is designed for upper body strength training. This doorway bar features multiple grip positions, allowing you to target different muscle groups. Easy to install and use, it is perfect for home workouts. Suitable for all fitness levels, from beginners to advanced athletes looking to build upper body strength.'),
(15, 'Jump Rope', 'Adjustable speed jump rope with ergonomic handles.', 'equipment', 14.99, 250, '2024-08-02', 'jump_rope.jpg', 'recently added', 'Jump rope is an excellent tool for cardio workouts and improving coordination. This adjustable speed rope features ergonomic handles for a comfortable grip. Suitable for all fitness levels, it helps enhance your cardiovascular endurance and agility. Ideal for home workouts or as part of a warm-up routine before more intense training.'),
(16, 'Gym Gloves', 'Padded gym gloves with wrist support.', 'accessories', 17.99, 100, '2024-08-02', 'gym_gloves.jpg', 'normal', 'Gym gloves provide protection and support during weightlifting and other workouts. These padded gloves come with wrist support to prevent injuries and improve grip strength. Ideal for athletes and fitness enthusiasts looking to enhance their performance and reduce the risk of calluses and blisters.'),
(17, 'Foam Roller', 'High-density foam roller for muscle massage and recovery.', 'accessories', 22.99, 120, '2024-08-02', 'foam_roller.jpg', 'normal', 'Foam roller is perfect for muscle massage and recovery. This high-density roller helps alleviate muscle soreness and improve flexibility. Ideal for athletes and fitness enthusiasts looking to enhance their recovery process. Suitable for use before or after workouts to improve mobility and reduce muscle tension.'),
(18, 'Resistance Bands', 'Set of 5 resistance bands with different resistance levels.', 'accessories', 19.99, 300, '2024-08-02', 'resistance_bands.jpg', 'normal', 'Resistance bands are a versatile tool for strength training and rehabilitation exercises. This set includes 5 bands with different resistance levels, allowing you to customize your workouts. Ideal for home workouts, physical therapy, and improving muscle tone. Suitable for all fitness levels, from beginners to advanced athletes.'),
(19, 'Ab Wheel', 'Ab wheel roller for core workouts.', 'accessories', 19.99, 90, '2024-08-02', 'ab_wheel.jpg', 'normal', 'Ab wheel is an effective tool for strengthening the core muscles. This roller helps improve abdominal strength and stability. Ideal for fitness enthusiasts looking to enhance their core workouts. Easy to use and suitable for all fitness levels, from beginners to advanced athletes seeking to improve their core strength.'),
(20, 'Balance Board', 'Wooden balance board for improving stability and core strength.', 'accessories', 34.99, 70, '2024-08-02', 'balance_board.jpg', 'normal', 'Balance board is designed to improve stability and core strength. This wooden board provides a challenging workout that enhances balance and coordination. Ideal for athletes and fitness enthusiasts looking to improve their performance. Suitable for use at home or in the gym, helping to strengthen the core muscles and improve overall stability.');
